# ReadTheDocs Configuration File
version: 2

# Define the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install --upgrade pip setuptools wheel
      - CODEARTIFACT_AUTH_TOKEN=$(python get_codeartifact_token.py)  # ✅ Fetch token
      - pip config set global.extra-index-url https://aws:$CODEARTIFACT_AUTH_TOKEN@cellarity-test-581351078906.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  configuration: conf.py
