name: Publish Python Package to AWS CodeArtifact

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Allows reading repository content

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::581351078906:role/GitHubActions_OIDC_role  # Replace with your IAM role ARN
          aws-region: us-east-1
          role-session-name: publish-python-package

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build twine

      - name: Build Package
        run: python -m build

      - name: Publish Package to AWS CodeArtifact
        run: |
          # Fetch a fresh AWS CodeArtifact authentication token
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain cellarity-test \
            --domain-owner 581351078906 \
            --region us-east-1 \
            --query authorizationToken \
            --output text)

          # Fetch the repository endpoint dynamically
          export REPOSITORY_URL=$(aws codeartifact get-repository-endpoint \
            --domain cellarity-test \
            --domain-owner 581351078906 \
            --repository python \
            --format pypi \
            --query repositoryEndpoint \
            --output text)

          echo "Using CodeArtifact Repository URL: $REPOSITORY_URL"

          # Upload the package using Twine
          twine upload --repository-url $REPOSITORY_URL \
            -u aws \
            -p $CODEARTIFACT_AUTH_TOKEN \
            dist/*

