name: Publish Python Package to AWS CodeArtifact

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Pulls the latest repository code

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::581351078906:role/GitHubActions_OIDC_role  # Update with your IAM role
          aws-region: us-east-1
          role-session-name: publish-python-package

      - name: Get CodeArtifact Repository URL
        id: get-repo-url
        run: |
          repo_url=$(aws codeartifact get-repository-endpoint \
            --domain cellarity-test \
            --domain-owner 581351078906 \
            --repository python \
            --format pypi \
            --region us-east-1 \
            --query repositoryEndpoint \
            --output text)
          echo "CODEARTIFACT_REPO_URL=$repo_url" >> $GITHUB_ENV

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build

      - name: Build Python Package
        run: python -m build

      - name: Install Twine
        run: pip install --upgrade twine

      - name: List Package Files
        run: ls -lh dist/

      - name: Upload Package to AWS CodeArtifact
        env:
          CODEARTIFACT_AUTH_TOKEN: ${{ secrets.CODEARTIFACT_AUTH_TOKEN }}
          CODEARTIFACT_REPO_URL: ${{ env.CODEARTIFACT_REPO_URL }}
        run: |
          twine upload --repository-url $CODEARTIFACT_REPO_URL \
            -u aws \
            -p $CODEARTIFACT_AUTH_TOKEN \
            dist/*
