name: Publish Python Package to AWS CodeArtifact

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Pulls the latest repository code

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::581351078906:role/GitHubActions_OIDC_role  # Update with your IAM role
          aws-region: us-east-1
          role-session-name: publish-python-package

      - name: Get CodeArtifact Repository URL
        run: |
          export CODEARTIFACT_REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain cellarity-test \
            --domain-owner 581351078906 \
            --repository python \
            --format pypi \
            --region us-east-1)
          echo "CODEARTIFACT_REPO_URL=$CODEARTIFACT_REPO_URL" >> $GITHUB_ENV

      - name: Login to AWS CodeArtifact (pip)
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain cellarity-test \
            --domain-owner 581351078906 \
            --region us-east-1 \
            --query authorizationToken \
            --output text)
          
          pip config set global.extra-index-url \
            https://aws:$CODEARTIFACT_AUTH_TOKEN@cellarity-test-581351078906.d.codeartifact.us-east-1.amazonaws.com/pypi/python/simple/

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build

      - name: Build Python Package
        run: python -m build

      - name: Install Twine
        run: pip install --upgrade twine

      - name: List Package Files
        run: ls -lh dist/

      - name: Upload Package to AWS CodeArtifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain cellarity-test \
            --domain-owner 581351078906 \
            --region us-east-1 \
            --query authorizationToken \
            --output text)

          twine upload --repository-url $CODEARTIFACT_REPO_URL \
            -u aws \
            -p $CODEARTIFACT_AUTH_TOKEN \
            dist/*
