name: Rotate AWS Keys and Update RTD

on:
  schedule:
    - cron: "0 0 1 */3 *"  # Runs every 90 days
  workflow_dispatch:  # Allows manual trigger

jobs:
  rotate-aws-keys:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::Y581351078906:role/GitHubActions_OIDC_role
          aws-region: us-east-1  # Change to your AWS region

      - name: Install Dependencies
        run: pip install requests boto3

      - name: Run Update Script
        env:
          RTD_API_TOKEN: ${{ secrets.RTD_API_TOKEN }}
        run: python scripts/update_rtd_aws_keys.py
